/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Candlewarmer.glb 
*/
import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Sculpts/Candlewarmer.glb')
  const { actions } = useAnimations(animations, group)
  //state to track animation play/pause


  useEffect(() => {
    if (actions) {
      actions["Action"]?.play(); // Replace with actual animation name
      actions["Action.001"]?.play(); // Replace with actual animation name
      actions["Action.002"]?.play(); // Replace with actual animation name
    }
   
    //The animation was playing as if there were animations on each object one after one using the for each mathod like
    //chatgpt told me to do so instead, I am running all of the animations which have names your able to see in the console.log
    //I did below and referenced the by name in the above if statement as indexes. This made the animation work correctly.
    // console.log(Object.keys(actions)[0])
    // Object.keys(actions).forEach(name => actions[name]?.play())
  }, [actions]);
  
  
  
  
  return (
    <group ref={group} {...props} dispose={null} scale={1.30} position={[-2, 0, -3]}>
      <group name="Scene">
        <group name="Mirror">
          <mesh name="Rod_connection_points" geometry={nodes.Rod_connection_points.geometry} material={materials.Material_3} position={[0.059, 0.385, 0.104]} scale={0.099} />
          <mesh name="Gold_rods" geometry={nodes.Gold_rods.geometry} material={materials.Material_4} position={[0.67, -0.096, 0.142]} rotation={[-0.078, -0.002, 0]} />
        </group>
        <group name="Lights" />
        <group name="Lights_1" position={[0, -1.407, 0]} scale={0.735} />
        <mesh name="Light_warmer" geometry={nodes.Light_warmer.geometry} material={materials.Material_0} position={[0, 0, 0.096]} />
        <mesh name="Top_cone" geometry={nodes.Top_cone.geometry} material={materials.Material_1} position={[-0.002, 0.483, 0.101]} rotation={[3.107, 0, 0]} scale={0.254} />
        <mesh name="Light_bulb" geometry={nodes.Light_bulb.geometry} material={materials.Material_2} position={[0.052, -0.103, 0.095]} scale={0.347} />
        <mesh name="Candle_stand" geometry={nodes.Candle_stand.geometry} material={materials.Material_8} position={[0.005, -1.955, 0.058]} scale={1.67} />
        <mesh name="Rod_connection_points001" geometry={nodes.Rod_connection_points001.geometry} material={materials.Material_3} position={[-0.059, 0.385, 0.104]} rotation={[-Math.PI, 0, 0]} scale={-0.099} />
        <mesh name="Gold_rods001" geometry={nodes.Gold_rods001.geometry} material={materials.Material_4} position={[-0.67, -0.096, 0.142]} rotation={[3.063, -0.002, 0]} scale={-1} />
        <mesh name="Candle_glass_container_" geometry={nodes.Candle_glass_container_.geometry} material={materials.Material_5} position={[0.005, -1.393, -1.646]} scale={0.898} />
        <mesh name="Candle_wax" geometry={nodes.Candle_wax.geometry} material={materials.Material_6} position={[0, -1.305, -1.646]} scale={[0.98, 0.637, 0.98]} />
        <mesh name="Wicks" geometry={nodes.Wicks.geometry} material={materials.Material_7} position={[0.039, -1.456, -1.99]} rotation={[0.158, 0, 0]} scale={0.656} />
      </group>
    </group>
  )
}

useGLTF.preload('/Sculpts/Candlewarmer.glb')
export default Model;