/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Stanleycup.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'


export function Model(props) {
  const { nodes, materials } = useGLTF('/Stanleycup.glb')
  const gltf = useGLTF('/Stanleycup.glb');
  console.log(gltf);
  
  
  return (
    <group {...props} dispose={null}>
      <group position={[0.003, 2.666, 0]} scale={[1, 0.205, 0.912]}>
        <mesh geometry={nodes.Lid_seal_1.geometry} materials={nodes.Lid_seal_1.materials} />
        <mesh geometry={nodes.Lid_seal_2.geometry} material={nodes.Lid_seal_2.material} />
        <mesh geometry={nodes.Lid_seal_3.geometry} material={nodes.Lid_seal_3.material} />
        <mesh geometry={nodes.Lid_seal_4.geometry} material={nodes.Lid_seal_4.material} />
        <mesh geometry={nodes.Lid_seal_5.geometry} material={nodes.Lid_seal_5.material} />
        <mesh geometry={nodes.Lid_seal_6.geometry} material={nodes.Lid_seal_6.material} />
        <mesh geometry={nodes.Lid_seal_7.geometry} material={nodes.Lid_seal_7.material} />
        <mesh geometry={nodes.Lid_seal_8.geometry} material={nodes.Lid_seal_8.material} />
        <mesh geometry={nodes.Lid_seal_9.geometry} material={nodes.Lid_seal_9.material} />
        <mesh geometry={nodes.Lid_seal_10.geometry} material={nodes.Lid_seal_10.material} />
        <mesh geometry={nodes.Lid_seal_11.geometry} material={nodes.Lid_seal_11.material} />
        <mesh geometry={nodes.Lid_seal_12.geometry} material={nodes.Lid_seal_12.material} />
      </group>
      <group position={[0, 1.966, 0.391]} scale={[0.133, 2.527, 0.133]}>
        <mesh geometry={nodes.Straw_1.geometry} material={nodes.Straw_1.material} />
        <mesh geometry={nodes.Straw_2.geometry} material={nodes.Straw_2.material} />
        <mesh geometry={nodes.Straw_3.geometry} material={nodes.Straw_3.material} />
      </group>
      <group position={[0, 2.646, 0]} scale={[1.237, 0.975, 1.237]}>
        <mesh geometry={nodes.Lid_2.geometry} material={nodes.Lid_2.material} />
        <mesh geometry={nodes.Lid_3.geometry} material={nodes.Lid_3.material} />
      </group>
      <group position={[0, 2.521, 0]} scale={[1.237, 0.825, 1.237]}>
        <mesh geometry={nodes.Lid_1_1.geometry} material={nodes.Lid_1_1.material} />
        <mesh geometry={nodes.Lid_1_2.geometry} material={nodes.Lid_1_2.material} />
      </group>
      <mesh geometry={nodes.Logo_new.geometry} material={nodes.Logo_new.material} position={[0.02, 2.02, -0.616]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.503} />
      <group position={[0, 1.557, 0]} scale={1.155}>
        <mesh geometry={nodes.Main_cup_container_1.geometry} material={nodes.Main_cup_container_1.material} />
        <mesh geometry={nodes.Main_cup_container_2.geometry} material={nodes.Main_cup_container_2.material} />
      </group>
      <group position={[0, 0.03, 0]} scale={1.093}>
        <mesh geometry={nodes.Base_1.geometry} material={nodes.Base_1.material} />
        <mesh geometry={nodes.Base_2.geometry} material={nodes.Base_2.material} />
        <mesh geometry={nodes.Base_3.geometry} material={nodes.Base_3.material} />
        <mesh geometry={nodes.Base_4.geometry} material={nodes.Base_4.material} />
      </group>
      <group position={[0, 0.578, 0]} scale={1.165}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={nodes.Cylinder_1.material} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={nodes.Cylinder_2.material} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={nodes.Cylinder_3.material} />
      </group>
      <directionalLight intensity={1} decay={2} color="#f3ede1" position={[0.467, 3.674, -0.471]} rotation={[3.119, 0.545, -3.06]} target={nodes.Light.target}>
        <primitive object={nodes.Light.target} position={[0, 0, -1]} />
      </directionalLight>
      <directionalLight intensity={1} decay={2} color="#e640d7" position={[0.898, 2.256, -1.529]} rotation={[-2.062, -0.629, -0.995]} target={nodes.Light_1_1.target}>
        <primitive object={nodes.Light_1_1.target} position={[0, 0, -1]} />
      </directionalLight>
      <mesh geometry={nodes.Handle_1.geometry} material={nodes.Handle_1.material} />
      <mesh geometry={nodes.Handle_2.geometry} material={nodes.Handle_2.material} />
      <mesh geometry={nodes.Handle_3.geometry} material={nodes.Handle_3.material} />
    </group>
  )
  
}

export default Model;
useGLTF.preload('/Stanleycup.glb')
