/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cutekitchen.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'


export function Model(props) {
  const { nodes, materials } = useGLTF('/cutekitchen.glb')
  return (
    <group {...props} dispose={null} scale={1.30} rotation={[0, Math.PI, 0]}>
      <group position={[0.503, 0, 0.897]}>
        <mesh geometry={nodes.Table_legs.geometry} material={materials.Material_12} position={[-0.207, -0.511, -0.273]} rotation={[0, 0, -0.03]} scale={0.604} />
      </group>
      <mesh geometry={nodes.Chair_.geometry} material={materials.Material_0} position={[0.811, -0.253, 2.26]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.551, 0.623, 0.623]} />
      <mesh geometry={nodes.Table_top.geometry} material={materials.Material_1} position={[0.497, -0.258, 0.892]} rotation={[0, 0, 0.014]} scale={[1.173, 1.006, 1.173]} />
      <mesh geometry={nodes.Window_outline.geometry} material={materials.Material_2} position={[1.522, 0.203, 1.96]} scale={[0.433, 0.516, 0.668]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.Material_3} position={[1.632, 0.22, 1.884]} rotation={[0, 0, -Math.PI / 2]} scale={[0.706, 0.401, 0.699]} />
      <mesh geometry={nodes.Left_blind.geometry} material={materials.Material_4} position={[1.279, 0.097, 1.797]} rotation={[0, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Window_panels.geometry} material={materials.Material_5} position={[1.64, 0.218, 1.918]} scale={0.264} />
      <mesh geometry={nodes.Cabinet_left.geometry} material={materials.Material_6} position={[1.341, 0.343, 0.472]} scale={[0.301, 0.435, 0.409]}>
        <mesh geometry={nodes.Cabinet_handle_1.geometry} material={materials.Material_7} position={[-0.565, -0.368, 0.043]} rotation={[Math.PI / 2, 0, 0]} scale={[0.093, 0.473, 0.051]} />
      </mesh>
      <mesh geometry={nodes.Cabinet_right_.geometry} material={materials.Material_8} position={[1.341, 0.343, 0.894]} scale={[0.301, 0.435, 0.409]}>
        <mesh geometry={nodes.Cabinet_handle.geometry} material={materials.Material_9} position={[-0.566, -0.368, 0.087]} rotation={[Math.PI / 2, 0, 0]} scale={[0.093, 0.473, 0.051]} />
      </mesh>
      <mesh geometry={nodes.Right_blind.geometry} material={materials.Material_10} position={[1.276, 0.097, 2.128]} rotation={[0, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Curtain_rod.geometry} material={materials.Material_11} position={[1.318, 0.426, 1.958]} rotation={[Math.PI / 2, 0, 0]} scale={[0.069, 0.086, 0.063]} />
      <mesh geometry={nodes.Right_wall.geometry} material={materials.Material_13} position={[0.641, -0.132, 2.674]} scale={[1.465, 1.429, 1.429]} />
      <mesh geometry={nodes.Left_wall.geometry} material={materials.Material_14} position={[1.541, -0.053, 1.472]} rotation={[0, 1.571, 0]} scale={[1.053, 1.429, 1.429]} />
      <mesh geometry={nodes.Refrigerator_.geometry} material={materials.Material_15} position={[0.127, -0.167, 2.194]} scale={[0.523, 1.142, 0.568]} />
      <mesh geometry={nodes.Fridge_handle_1.geometry} material={materials.Material_16} position={[0.342, 0.137, 1.883]} rotation={[-0.001, 0.007, 0.002]} scale={[0.028, 0.28, 0.031]} />
      <mesh geometry={nodes.Fridge_handle.geometry} material={materials.Material_17} position={[0.34, -0.383, 1.882]} scale={[0.028, 0.437, 0.031]} />
      <mesh geometry={nodes.Floor.geometry} material={materials.Material_18} position={[0.64, -0.909, 1.467]} rotation={[-Math.PI / 2, 0, 0]} scale={1.672} />
      <mesh geometry={nodes.Stanley_cup.geometry} material={materials.Material_19} position={[0.305, -0.108, 0.699]} scale={0.089} />
      <mesh geometry={nodes.Head.geometry} material={materials.Material_20} position={[0.779, -0.431, 2.163]} rotation={[Math.PI, 0, -2.874]} scale={[0.263, 0.223, 0.226]} />
      <mesh geometry={nodes.Table_legs001.geometry} material={materials.Material_12} position={[0.71, -0.511, 0.624]} rotation={[-Math.PI, 0, -0.03]} scale={-0.604} />
      <mesh geometry={nodes.Table_legs002.geometry} material={materials.Material_12} position={[0.296, -0.511, 1.171]} rotation={[0, 0, 3.111]} scale={-0.604} />
      <mesh geometry={nodes.Table_legs003.geometry} material={materials.Material_12} position={[0.71, -0.511, 1.171]} rotation={[-Math.PI, 0, 3.111]} scale={0.604} />
    </group>
  )
}

useGLTF.preload('/cutekitchen.glb')
export default Model;