/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/Donuts/donuts614.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Donuts = (props) => {
  const { nodes, materials } = useGLTF('./Donuts/donuts614.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DONUT.geometry} material={materials.ICING_baked} position={[0.178, 0.276, 0.115]} rotation={[-1.717, -0.122, 0.715]}>
        <mesh geometry={nodes.ICING.geometry} material={materials['Material.002']} position={[0, -0.019, 0]} />
      </mesh>
      <mesh geometry={nodes.DONUT_20.geometry} material={materials['Material.001']} position={[-0.092, 0.066, 0.045]} rotation={[0.559, 0.602, 2.088]}>
        <mesh geometry={nodes.ICING001.geometry} material={materials['Material.002']} position={[0, -0.019, 0]} />
      </mesh>
      <mesh geometry={nodes.Sprinkle.geometry} material={materials.Sprinkle_baked} position={[0.318, 0.018, 0.142]} />
      <mesh geometry={nodes.Small_sprinkle.geometry} material={materials['Sprinkle 1']} position={[0.434, 0.063, 0.091]} rotation={[-2.629, 0, 0]} scale={0.034} />
      <mesh geometry={nodes.medium_sprinkle.geometry} material={materials['Sprinkle 1']} position={[0.433, 0.062, 0.092]} rotation={[-2.629, 0, 0]} scale={0.034} />
      <mesh geometry={nodes.curved_sprinkle.geometry} material={materials['Sprinkle 1']} position={[0.432, 0.062, 0.092]} rotation={[-2.629, 0, 0]} scale={0.034} />
    </group>
  )
}
export default Donuts;
useGLTF.preload('./Donuts/donuts614.glb')
