/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 smallblendermatcha.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Sculpts/smallblendermatcha.glb')
  return (
    <group {...props} dispose={null} scale={.50} position={[-5, 0, 0]}>
      <mesh geometry={nodes.Cookie.geometry} material={materials['Material_0.001']} position={[0.002, 1.194, 0.444]} rotation={[0.026, 0.75, -0.011]} scale={[0.457, 0.546, 0.603]} />
      <mesh geometry={nodes.Box.geometry} material={materials['Material_1.001']} position={[0, -1.397, 0]} scale={[1.452, 1.243, 1.483]} />
      <mesh geometry={nodes.Glass.geometry} material={materials['Material_2.001']} position={[0, -0.071, 0]} />
      <mesh geometry={nodes.Tube.geometry} material={materials['Material_3.001']} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material_4.001']} position={[-0.391, 1.48, -0.228]} rotation={[-0.094, -0.022, 0.188]} scale={0.198} />
      <mesh geometry={nodes.Ice.geometry} material={materials['Material_5.001']} position={[-0.019, 1.111, 0.323]} rotation={[0, 0, -2.95]} scale={0.21} />
      <mesh geometry={nodes.Ice_2.geometry} material={materials['Material_6.001']} position={[-0.221, 1.11, -0.005]} rotation={[-0.68, 0, Math.PI]} scale={0.21} />
      <mesh geometry={nodes.Liquid.geometry} material={materials['Material_7.001']} position={[0, 0.019, 0]} scale={[1, 1.03, 1]} />
    </group>
  )
}

useGLTF.preload('/smallblendermatcha.glb')
export default Model;